M48
; DRILL file {KiCad (7.0.0)} date Fri Apr 21 18:23:13 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-21T18:23:13-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X28.612Y-21.173
X33.462Y-21.173
T2
X28.312Y-18.143
X33.762Y-18.143
T3
X15.748Y-19.05
X15.748Y-75.692
X60.198Y-19.05
X60.198Y-75.692
T0
M30
